# Meta information for the project
name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-05-04"
send_metrics = false
account_id = "6366bbbb137f6c69722860afb9d4747b"

[[r2_buckets]]
# This is the bucket (storage space) that will be used to store the files that are uploaded to the CDN
binding = "CDN_BUCKET"
bucket_name = "cdn"
preview_bucket_name = "cdn"
